// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: entry.sql

package db

import (
	"context"
	"database/sql"

	"github.com/shopspring/decimal"
)

const createEntry = `-- name: CreateEntry :execresult
INSERT INTO entries
(
    account_id,
    amount
)
VALUES
    (?, ?)
`

type CreateEntryParams struct {
	AccountID int64           `json:"accountID"`
	Amount    decimal.Decimal `json:"amount"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEntry, arg.AccountID, arg.Amount)
}

const deleteEntry = `-- name: DeleteEntry :execresult
DELETE FROM entries
WHERE id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEntry, id)
}

const getEntry = `-- name: GetEntry :one
SELECT
    id, account_id, amount, created_at
FROM
    entries
WHERE
    id = ?
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT
    id, account_id, amount, created_at
FROM
    entries
ORDER BY
    id ASC
LIMIT ? OFFSET ?
`

type ListEntriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
